"""Complaint model for MongoDB"""
from datetime import datetime
from typing import Optional, List


def complaint_document(data) -> dict:
    """Create a complaint document for MongoDB"""
    now = datetime.utcnow()
    return {
        "complaint_id": None,  # Will be generated by service
        "complaintId": None,
        "user_id": None,
        "citizenId": None,
        "createdBy": None,
        "citizenName": None,
        "citizenEmail": None,
        "citizenPhone": None,
        "district_id": None,
        "districtId": None,
        "districtName": None,
        "district": None,
        "ward_id": data.ward_id,
        "wardId": data.ward_id,
        "wardName": None,
        "ward": None,
        "inspector_id": None,
        "worker_id": None,
        "complaint_type": data.complaint_type,
        "complaintType": data.complaint_type,
        "issueType": data.complaint_type,
        "description": data.description,
        "complaintDescription": data.description,
        "status": "OPEN",
        "priority": data.priority if hasattr(data, "priority") else "MEDIUM",
        "latitude": data.latitude,
        "longitude": data.longitude,
        "address": data.address if hasattr(data, "address") else None,
        "landmark": data.landmark if hasattr(data, "landmark") else None,
        "image_urls": data.image_urls if hasattr(data, "image_urls") else [],
        "images": data.image_urls if hasattr(data, "image_urls") else [],
        "proof_images": [],
        "citizen_note": data.citizen_note if hasattr(data, "citizen_note") else None,
        "inspector_note": None,
        "worker_note": None,
        "rejection_reason": None,
        "deadline": data.deadline if hasattr(data, "deadline") else None,
        "created_at": now,
        "createdAt": now,
        "updated_at": now,
        "updatedAt": now,
        "closed_at": None,
    }


def complaint_history_document(data) -> dict:
    """Create a complaint history document for audit trail"""
    return {
        "complaint_id": data.complaint_id,
        "action": data.action,
        "old_status": data.old_status if hasattr(data, "old_status") else None,
        "new_status": data.new_status if hasattr(data, "new_status") else None,
        "performed_by": data.performed_by,
        "role": data.role,
        "remarks": data.remarks if hasattr(data, "remarks") else None,
        "timestamp": datetime.utcnow()
    }


def complaint_response(doc) -> dict:
    """Format complaint document for API response"""
    if not doc:
        return None
    
    doc["_id"] = str(doc.get("_id", ""))
    
    d_name = doc.get("district") or doc.get("district_name") or doc.get("districtName") or "Not Available"
    w_name = doc.get("ward") or doc.get("ward_name") or doc.get("wardName") or "Not Available"
    
    citizen_name = doc.get("citizenName") or doc.get("citizen_name") or "Not Available"
    citizen_email = doc.get("citizenEmail") or doc.get("citizen_email") or "Not Available"
    citizen_phone = doc.get("citizenPhone") or doc.get("citizen_phone") or "Not Available"
    
    c_id = str(doc.get("user_id") or doc.get("citizenId") or doc.get("createdBy") or "")
    
    doc["complaintId"] = doc.get("complaint_id") or "Not Available"
    doc["citizenId"] = c_id or "Not Available"
    doc["createdBy"] = c_id or "Not Available"
    doc["citizenName"] = citizen_name
    doc["citizenEmail"] = citizen_email
    doc["citizenPhone"] = citizen_phone
    
    doc["district_id"] = str(doc.get("district_id") or "") or "Not Available"
    doc["districtId"] = str(doc.get("district_id") or "") or "Not Available"
    doc["district_name"] = d_name
    doc["districtName"] = d_name
    doc["district"] = d_name
    
    doc["ward_id"] = str(doc.get("ward_id") or "") or "Not Available"
    doc["wardId"] = str(doc.get("ward_id") or "") or "Not Available"
    doc["ward_name"] = w_name
    doc["wardName"] = w_name
    doc["ward"] = w_name
    
    doc["complaint_type"] = doc.get("complaint_type") or "Not Available"
    doc["complaintType"] = doc.get("complaint_type") or "Not Available"
    doc["issueType"] = doc.get("complaint_type") or "Not Available"
    
    doc["description"] = doc.get("description") or "Not Available"
    doc["complaintDescription"] = doc.get("description") or "Not Available"
    
    doc["status"] = doc.get("status") or "Not Available"
    doc["priority"] = doc.get("priority") or "Not Available"
    doc["address"] = doc.get("address") or "Not Available"
    doc["landmark"] = doc.get("landmark") or "Not Available"
    
    doc["image_urls"] = doc.get("image_urls") or doc.get("images") or []
    doc["images"] = doc.get("images") or doc.get("image_urls") or []
    
    doc["createdAt"] = doc.get("created_at")
    doc["updatedAt"] = doc.get("updated_at")
    
    return doc
